### ISSUE TITLE
TypeError: Object [object Object] has no method 'observe'

### ISSUE THREAD

**Issue by mikemeier** [peerlibrary/meteor-related#8]
Hi, this package would actually exactly do what I need, unfortunately i get this error when I publish with this.related:

```
TypeError: Object [object Object] has no method 'observe'
```

My publish method looks like this:

```
Meteor.publish('owngroup-request-users', function () {
    check(this.userId, String);

    this.related(function (group) {
            if (!group.requests) {
                return;
            }

            return Meteor.users.find({_id: {$in: group.requests}}, {
                fields: {
                    statusConnection: true,
                }
            });
        },
        Groups.findOne({owner: this.userId}, {fields: {requests: true}})
    );
});
```

I'm using Meteor 1.2.1

**Comment by mitar** [comment]
Hm, can you provide a stack trace at least? Or a running reproduction.

Also, I would suggest you start using [reactive-publish](https://github.com/peerlibrary/meteor-reactive-publish).

**Comment by mikemeier** [comment]
I'll check out another package.

Stack trace:

```
Exception from sub owngroup-request-users id 8nnhR6YbZF9g5ECak { stack: 'TypeError: Object [object Object] has no method \'observe\'\n    at _fn (packages/peerlibrary_related/packages/peerlibrary_related.js:109:1)\n    at [object Object].publish.related (packages/peerlibrary_related/packages/peerlibrary_related.js:137:1)\n    at [object Object].<anonymous> (server/publications/group/owngroupPublications.js:23:10)\n    at [object Object].<anonymous> (packages/peerlibrary_related/packages/peerlibrary_related.js:157:1)\n    at packages/matb33_collection-hooks/collection-hooks.js:275:1\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at [object Object]._handler (packages/matb33_collection-hooks/collection-hooks.js:274:1)\n    at maybeAuditArgumentChecks (livedata_server.js:1698:12)\n    at [object Object]._.extend._runHandler (livedata_server.js:1023:17)\n    at [object Object].subscriptionProto._runHandler (packages/meteorhacks_kadira/lib/hijack/wrap_subscription.js:12:1)',
```

**Comment by mitar** [comment]
Oh, I see the problem. You are using `findOne`. It should be a cursor, not a element you are returning.

**Comment by mikemeier** [comment]
Thanks for quick answer!
